name: CI - WebUI

on: [pull_request, push]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.head_ref != '' }}

jobs:
  ci:
    name: Check
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    defaults:
      run:
        working-directory: src/webui/www

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install tools
        run: |
          npm install
          npm ls
          echo "::group::npm ls --all"
          npm ls --all
          echo "::endgroup::"

      - name: Run tests
        run: npm test

      - name: Lint code
        id: lint
        continue-on-error: true
        run: npm run lint

      - name: Format code
        id: format
        continue-on-error: true
        run: |
          npm run format
          git diff --exit-code

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          config-file: .github/workflows/helper/codeql/js.yaml
          languages: javascript

      - name: Run CodeQL analysis
        id: codeql
        continue-on-error: true
        uses: github/codeql-action/analyze@v3

      - name: Check for failures
        if: always()
        run: |
          if [[ "${{ steps.lint.outcome }}" != "success" ]]; then
            echo "Linting failed"
            exit_code=1
          fi

          if [[ "${{ steps.format.outcome }}" != "success" ]]; then
            echo "Code formatting check failed"
            exit_code=1
          fi

          if [[ "${{ steps.codeql.outcome }}" != "success" ]]; then
            echo "CodeQL analysis failed"
            exit_code=1
          fi

          exit ${exit_code:-0}
